version: 0.2
env:
  variables:
    KUDU_VERSION: "1.4.0"
    DOCKER_REPO: "amfoerster/apache-kudu" # No trailing slash
    PARALLEL: "8"
    DOCKER_USER: "amfoerster"
    LATEST: true
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Logging into Docker Hub...
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --build-arg KUDU_VERSION=$KUDU_VERSION -t kudu:$KUDU_VERSION -t kudu:latest .
      - docker tag kudu:$KUDU_VERSION $DOCKER_REPO:$KUDU_VERSION
        #      - docker tag kudu:latest $DOCKER_REPO:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $DOCKER_REPO:$KUDU_VERSION
        #      - docker push $DOCKER_REPO:latest
