version: 0.2
env:
  variables:
    KUDU_VERSION: "1.5.0"
    DOCKER_REPO: "amfoerster/apache-kudu" # No trailing slash
    PARALLEL: "8"
    DOCKER_USER: "amfoerster"
    IMAGE: "centos:7"
    LATEST: true
phases:
  pre_build:
    commands:
      - codebuild/pre_build
  build:
    commands:
      - codebuild/build
  post_build:
    commands:
      - codebuild/post_build
